export const IMAGES = {
  logo: "/assets/onluyenLogo.png",
  book: "/assets/book-open-text.svg",
  earth: "/assets/earth.svg",
  house: "/assets/house.svg",
  school: "/assets/school.svg",
  waves: "/assets/waves.svg",
  cuteDuck: "/assets/cuteDuck.gif",
  hugDuck: "/assets/duckHug.gif",
  arrowRight: "/assets/chevron-right.png",
  searchIcon: "/assets/search.png",
  statsitcIcon: "/assets/statistic.svg",
  courseIcon: "/assets/course.svg",
  questionIcon: "/assets/question.svg",
  examIcon: "/assets/exam.svg",
  bars: "/assets/bars.svg",
};
